### PR TITLE
Remove custom PrimitivePicklers

### PR DESCRIPTION
**Pull request by eed3si9n**
This creates type aliases for the following picklers:

-  type PrimitivePicklers = scala.pickling.pickler.PrimitivePicklers
-  type PrimitiveArrayPicklers = scala.pickling.pickler.PrimitiveArrayPicklers
-  type RefPicklers = scala.pickling.pickler.RefPicklers

VectorPicklers, ListPicklers, ArrayPicklers, and SeqPicklers are still needed for emitting $type hints on each element.

### CODE REVIEW

**Comment by jsuereth** [comment]
@eed3si9n can you rebase these?

**Comment by havocp** [comment]
We could drop the type aliases right? my general feeling is that to write a handcoded pickler or custom "pickler cake" you'd use pickling directly, and that our job in sbt.serialization is to prebake one possible set of defaults (staticonly, remove format customizability) and give a convenient way to import those defaults. But I guess this philosophical issue is what we need to discuss on Monday.
I'm fine with not holding up this PR over those aliases. I don't currently understand the serialization vs CoreProtocol split.

**Comment by havocp** [comment]
PR looks good otherwise but raises obvious question of can we modify pickling itself to give the necessary info for $type support.

**Comment by jsuereth** [comment]
where is it we want the $type that's causing issues?  Each underlying element?  That should be determined by the nested pickler anyway....

**Comment by eed3si9n** [comment]
I think I used to call pickler, but the new JSON format might be using builder directly. Not sure if that changes anything.

**Comment by jsuereth** [comment]
Ok, let's merge this as is. I'd like to understand what's happening with the array picklers though.

**Pull request merged**
