### PR TITLE
Bump to sbt 0.13.9-RC2

### PR DESCRIPTION
**Pull request by jsuereth**
Review by @eed3si9n or @corruptmemory

### CODE REVIEW

**Comment by jsuereth** [comment]
Failures appear to be new travis policy on log length.  Will have to look into some kind of fix in our printlns

**Comment by eed3si9n** [comment]
The PR LGTM, but I'd like to see Travis run if it's not too much work to get it going again.

**Comment by corruptmemory** [comment]
Also, LGTM.

**Comment by jsuereth** [comment]
@eed3si9n Ok, when you have a chane check out the new IT runner, which is less chatty on the success case.

**Comment by jsuereth** [comment]
got an LGTM from @corruptmemory on the IT fixes via gchat

**Pull request merged**
