### PR TITLE
Make Protocol.scala only contain Message, move "core plugin" events out

### PR DESCRIPTION
**Pull request by havocp**
This should hopefully be less confusing for future developers.

### CODE REVIEW

**Comment by jsuereth** [comment]
@havocp  this no longer merges cleanly

**Comment by jsuereth** [comment]
@havocp this doens't merge cleanly either

**Comment by havocp** [comment]
Merged but wait for tests here, I didn't run them locally

**Comment by havocp** [comment]
2/3 green, going to merge this.

**Pull request merged**
