### PR TITLE
Make it work with latest pickling

### PR DESCRIPTION
**Pull request by havocp**
Just realized my second commit will make tests fail with M1 though. Oops. First commit should be safe against M1.

### CODE REVIEW

**Comment by havocp** [comment]
Removed the commit that put the duck type tests back, for now.

**Comment by jsuereth** [comment]
this LGTM, but the tests are all failing

**Comment by havocp** [comment]
Hey, only 3 of 4 are failing.

Not sure it's related to this change, but maybe it is.

**Comment by jsuereth** [comment]
No, it's the same failure state we had before, odd that 2 succeed and 2 do not of the 4 jvms.  Keeps pointing at timing issues....

**Comment by jsuereth** [comment]
All the fialrues seem to be around 'sleeping for death' on travis.  Maybe I'll bump the timeout forthat...

**Comment by jsuereth** [comment]
@havocp you missed the migration to pickling M2 in the build, or was that on purpose?

**Comment by havocp** [comment]
No I missed it. didn't know m2 existed. The only thing enabled by migrating should be that we can remove @ignore from those two duck type tests.

**Comment by jsuereth** [comment]
@havocp can you rebase this against master?

**Comment by havocp** [comment]
Done and also unignored duck type tests

**Pull request merged**
