### PR TITLE
Upgrade to core-next 0.1.0-M3, serialization 0.1.0-M2, pickling 0.10.0-M...

### PR DESCRIPTION
**Pull request by havocp**
...4

### CODE REVIEW

**Comment by eed3si9n** [comment]
Waiting on Travis but LGTM

**Comment by corruptmemory** [comment]
My only comment is shouldn't `Pickler[T] with Unpickler[T]` really be given a name?  It appears in quite a few places.

**Comment by eed3si9n** [comment]
@corruptmemory We tried shaving that yak in multiple ways (tuple, extends, type alias), and it caused macro/implicit pains so we settled on not doing it.

**Comment by corruptmemory** [comment]
Hrm... such is life I guess.

**Pull request merged**
